apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      automountServiceAccountToken: false
      containers:
        - name: recommendation
          envFrom:
            - configMapRef:
                name: recommendation-service-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: ghcr.io/soldevlife-assesment-2024-s1/recommendation-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
